### ISSUE TITLE
Quote marks in Title will break code 

### ISSUE THREAD

**Issue by pekspro** [jeppevammenkristensen/auto-spectre#19]
If I use this:

```C#
[TextPrompt(Title = "Add \"item")] public int[] IntItems { get; set; } = Array.Empty<int>();
```

The generated code will not compile. Consider use [SymbolDisplay.FormatLiteral](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.csharp.symboldisplay.formatliteral) to properly escape strings.

**Comment by jeppevammenkristensen** [comment]
Thanks for the info regarding SymbolDisplay.FormatLiteral. I did not know about that one.  I have adjusted the code and pushed a new preview package. It's here https://www.nuget.org/packages/AutoSpectre.SourceGeneration/0.8.2-preview-01

**Comment by pekspro** [comment]
Wow, I’m impressed how quickly you solved that :-)

It’s actually not nothing I need, just something I discovered and wanted to let you know.

**Comment by jeppevammenkristensen** [comment]
Fortunately had some spare time. Thanks for reporting it, I'm not sure I would have caught that by myself.
